### ISSUE TITLE
Personalized recommendation of POI

### ISSUE THREAD

**Issue by elindgren** [Mobile-and-Ubiquitous-Computing-2020-1/team4#39]
Solves the problem of overlapping geofences. 

- [ ] In case of overlapping geofences A and B, recommend geofence A based on the probability of it's category p(C_A). 
- [ ] In case of the same category, set p(C_A) = p(C_B) = 0.5 (could update this?)
- [ ] The probabilities p(C_i) is calculated from the score of the category C_i. The probabilities would be calculated as p(C_A) = s_C_A/(s_C_A+s_C_B). The vector of scores C **is** kept in the database, see #36.
- [ ] The vector **C** should hold a score for each category C_i. When the user likes a place, increase this score by +2, +1 if they just open the notification, -1 if they don't open the notification and -2 if they dislike it. 
- [ ] Initialize **C** uniformly.
